export const background = 'bg-sky-50 text-gray-600'
export const primary = 'bg-sky-900 text-white'
export const primaryText ='text-sky-900'
export const textColor = 'text-gray-600'
export const primaryVariant = 'bg-sky-200 text-gray-600'
